name: Create PR to main

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: "Sync master to main"
          body: "Automated PR from master to main"
