name: Create PR from master to main

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create PR from master to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: master
          destination_branch: main
          pr_title: "Sync changes from master to main"
          pr_body: |
            This pull request was created automatically to sync changes from `master` to `main`.
          github_token: ${{ secrets.GITHUB_TOKEN }}
