name: Release

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Version bump
        run: pnpm changeset version

      - name: Get version
        id: get_version
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Copy .fmp12 with version
        run: |
          cp Filemaker/ListViewAddon.fmp12 Filemaker/ListViewAddon_v${{ steps.get_version.outputs.version }}.fmp12

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json .changeset/ .github
          git commit -m "chore: version bump v${{ steps.get_version.outputs.version }}"
          git push

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: |
            Filemaker/ListViewAddon_v${{ steps.get_version.outputs.version }}.fmp12
